name: minha_aula_cim
description: "Confira o local e o horário de suas aulas com mais facilidade e agilidade!"
publish_to: 'none'

version: 1.0.6+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4
  flutter_auto_cache: ^0.0.4
  intl: ^0.20.2
  uno: ^1.1.12
  envied: ^1.1.1
  result_dart: ^1.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/
